#!/usr/bin/env python3
"""Established swipe layout with all review decisions and inline paired timings."""
from pathlib import Path
import html,json,statistics,sys
root=Path(sys.argv[1]);m=json.loads((root/'manifest.json').read_text());esc=lambda x:html.escape(str(x));cards=[]
for row in m['rows']:
 for source in ['iso','milano1','optical','hdr']:
  prefix=row['id']+'--'+source;metrics=root/'images'/(prefix+'-metrics.json')
  if not metrics.exists():continue
  try:d=json.loads(metrics.read_text())
  except (ValueError,OSError):continue
  if d.get("nonfinite")!=0 or not d.get("runs"):continue
  timings=[]
  for key,label in [('gpu','GPU'),('wall','Wall')]:
   a=statistics.median(r['old_'+key] for r in d['runs']);b=statistics.median(r['new_'+key] for r in d['runs']);delta=[100*(r['new_'+key]/r['old_'+key]-1) for r in d['runs']]
   timings.append(f'<tr><td>{label}</td><td>{a:.3f} ms</td><td>{b:.3f} ms</td><td>{b-a:+.3f} ms ({100*(b/a-1):+.1f}%)</td><td>{min(r["new_"+key]-r["old_"+key] for r in d["runs"]):+.3f} to {max(r["new_"+key]-r["old_"+key] for r in d["runs"]):+.3f} ms ({min(delta):+.1f}% to {max(delta):+.1f}%)</td></tr>')
  source_label={'iso':'ISO chart','milano1':'iPhone scene 1','optical':'Synthetic optical chart','hdr':'HDR point sources'}[source]
  before='images/'+prefix+'-before.png';after='images/'+prefix+'-after.png'
  assert (root/before).is_file() and (root/after).is_file()
  cards.append(f'''<article><h2>{esc(row['label'])} · {source_label}</h2><p>{esc(row['rationale'])}</p><div class="compare"><img src="{esc(after)}" loading="lazy"><div class="before"><img src="{esc(before)}" loading="lazy"></div><span class="divider"></span><span class="label left">Baseline · {row.get('baseline_engine','1.69')} engine / prior recipe</span><span class="label right">Candidate · {esc(row.get('candidate_engine','1.70 engine'))} / proposed recipe</span><input type="range" min="0" max="100" value="50" aria-label="Compare {esc(row['label'])}"></div><p>{d['width']} × {d['height']} · finite components: PASS · scene-linear RGB mean difference {d['mae']:.6f}. {len(d['runs'])} paired runs, {d['frames']} frames after four warm-ups; order alternates.</p><table><thead><tr><th>Timing</th><th>Baseline median</th><th>Candidate median</th><th>Median change</th><th>Paired spread</th></tr></thead><tbody>{''.join(timings)}</tbody></table></article>''')
rows=''.join(f"<tr><td>{esc(r['label'])}</td><td>{esc(r['decision'])}</td><td>{esc(r['rationale'])}</td><td>{esc(', '.join(k+' → '+str(v) for k,v in r['changes'].items()) or 'Unchanged')}</td><td>{esc('; '.join(r['warnings']) or 'No validator dependency flags')}</td><td>{esc(r['status'])}</td></tr>" for r in m['rows'])
# Reuse exactly the established optical-drift presentation stylesheet.
repo=Path(__file__).resolve().parent.parent
source=(repo/'scripts/build-optical-drift-preset-report.py').read_text();css=source.split('<style>',1)[1].split('</style>',1)[0].replace('{{','{').replace('}}','}')
css+='table{width:100%;border-collapse:collapse;font-size:13px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #303840;padding:9px}.inventory{overflow-x:auto}.inventory table{min-width:1100px}p{color:#aab3ba}'
doc=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lens Debaser 1.70 Factory Review</title><style>{css}</style></head><body><header><h1>Factory preset review · 1.70</h1><p>All {m['original_count']} released presets reviewed structurally. {m['range_revision_count']} contain values outside current control bounds; candidate corrections are proposals. {m['candidate_count']-m['original_count']} new treatments prepared. No visual acceptance or release promotion is implied.</p><p>Comparisons measure the combined engine and recipe change, using exact authored released values for original presets. Legacy host clamping can differ from this direct-render baseline; verify affected presets in Resolve before acceptance. New creative baselines use the named existing treatment with proposed range normalization. New demonstrations compare with neutral, except isolated Amount/Angle variants which use the matched 45% / 55° treatment.</p><p>960px images assess framing and character. Native-resolution follow-up is required for sharpness decisions. These timings measure the displayed source/resolution, not 4K playback. Negative differences do not establish speedups. Depth, motion and host UI require separate checks.</p><p>{esc('Guide gaps: '+', '.join(m.get('guide_audit',{}).get('undocumented_new_controls',[])))}. {esc(m.get("review_context", "New creative families are deferred."))}</p><p>{len(cards)} completed comparisons. {'User CLI rendering and benchmarking pending.' if not cards else 'Awaiting joint visual and benchmark acceptance.'}</p></header><main>{''.join(cards)}<article><h2>Complete library decisions and proposed changes</h2><div class="inventory"><table><thead><tr><th>Preset</th><th>Proposal</th><th>Reason</th><th>Changes</th><th>Dependency notes</th><th>Acceptance</th></tr></thead><tbody>{rows}</tbody></table></div></article></main><script>document.querySelectorAll('.compare').forEach(box=>{{const input=box.querySelector('input'),layer=box.querySelector('.before'),line=box.querySelector('.divider');const update=()=>{{const v=Number(input.value);layer.style.clipPath=`inset(0 ${{100-v}}% 0 0)`;line.style.left=v+'%'}};input.addEventListener('input',update);update()}})</script></body></html>'''
(root/'index.html').write_text(doc);print(f'Built review with {len(cards)} comparisons and {len(m["rows"])} inventory rows.')
