#!/usr/bin/env python3
"""Human-readable candidate control inventory and processing-order audit."""
from pathlib import Path
import html,json,re,sys
repo=Path(__file__).resolve().parent.parent
source=(repo/'src/ofx/LensDebaserPlugin.cpp').read_text();header=(repo/'include/LDBControlLayout.h').read_text()
def rows(kind):
 block=header.split(f'inline constexpr {kind} '+('groups' if kind=='Group' else 'controls')+'[] = {',1)[1].split('};',1)[0]
 return [json.loads('['+line.strip()[1:-2]+']') for line in block.splitlines() if line.strip().startswith('{')]
groups=rows('Group');controls=rows('Control');spec=source.split('const DoubleSpec kSpecs[] = {',1)[1].split('struct Preset',1)[0]
values={i:(label,default.strip(),lo.strip(),hi.strip()) for i,label,default,lo,hi in re.findall(r'\{"([^"]+)",\s*"([^"]+)",\s*([^,]+),\s*([^,]+),\s*([^,]+),',spec)}
e=html.escape
special={'effectSize':'Frame Relative (default) / Fixed Pixels','projectionModel':'Off / Equidistant / Stereographic','projectionFraming':'Fill Frame / Balanced / Preserve Centre Scale','opticalCenter':'X/Y: 0–1; default 0.5/0.5','fieldCenter':'X/Y: 0–1; default 0.5/0.5','workingSpace':'Input encoding; unchanged options','diagnosticView':'Diagnostic modes; unchanged options','preset':'Preset menu','loadPreset':'Load file','savePreset':'Save file','captureGate':'Capture format choices; unchanged','apertureShape':'Circular / Polygon / Oval','apertureBladeCount':'3–16; default 6','opticalDriftMode':'Radial / Tangential / Directed','depthMode':'Depth interpretation choices; unchanged','prismDistribution':'Linear Edge / Uniform / Bilateral / Radial / Inverse'}
def group(id):
 _,label,parent,hint=next(g for g in groups if g[0]==id)
 own=[c for c in controls if c[1]==id];children=[g for g in groups if g[2]==id]
 content=''
 if own:
  content='<table><thead><tr><th>Control</th><th>Default / range or type</th></tr></thead><tbody>'
  for key,_,name,h in own:
   if key in values:
    old,d,lo,hi=values[key];info=f'{d} · {lo} to {hi}'
   else:old=name;info=special.get(key,'Color; existing default and range unchanged')
   content+=f'<tr><td>{e(name)}'+(f'<small>Previously: {e(old)}</small>' if old!=name else '')+(f'<small>{e(h)}</small>' if h else '')+f'</td><td>{e(info)}</td></tr>'
  content+='</tbody></table>'
 content+=''.join(group(g[0]) for g in children)
 return f'<details open><summary>{e(label)}</summary><p>{e(hint)}</p>{content}</details>'
findings=['Projection is first in Geometry & Field, ahead of distortion. Its menu is Model, followed by Amount, half-diagonal Field Angle and Framing. Fill Frame describes the observed crop/magnification more clearly than Full frame.','Anamorphic Field Aspect and Cylindrical Distortion stay with geometry. Anamorphic Fringing is with chromatic aberration. Anamorphic Flare is in Light & Color, with separate Streak Shape, Reflections and Diffraction Rays subgroups.','Depth & Focus, Coma, Aperture & Bokeh, field focus and detail are together. Optical Drift remains with the aperture that enables it.','Vignette and Image Circle are together in Light & Color. Mechanical Vignette opens the boundary controls it uses. Transmission comes before the scatter groups because it affects the direct image before extraction.','Field Transition Width and Chromatic Transition Width replace ambiguous Falloff labels. Full Defocus Distance labels the actual depth endpoint, which has different semantics.','Geometric Swirl and Bokeh Swirl are distinct. Optical Center is exposed directly in Geometry & Field because projection, distortion, vignette and flare share it. Field Center stays independently adjustable in Shared Field.','Capture Context and Look Macros explain that they modify optical parameters. Lens Character replaces Advanced: variation, wear and contamination affect several stages rather than forming a final processing pass.','All configured controls, including non-default colors and dormant test values, open their group and every ancestor. Dependencies also expose Shared Field, mechanical coverage and highlight threshold controls where relevant.','Output contains Effect Blend. Processing is now Input & Diagnostics, and Input Color Space still must match the encoding entering the plug-in.','Stable parameter IDs, preset keys, choice indices, ranges, defaults and shader behavior are preserved. Main-release presentation and guide remain unchanged until integration.']
flow=['Capture/Look resolve parameter contributions and host pixel scaling; optional depth is prepared. Input is decoded to linear AP1.','Direct optics: projection → conventional/cylindrical distortion and gated/peripheral mapping → glass/prism offsets → chromatic/focus/detail sampling → vignette/transmission/wear density. Several controls share fields rather than operating as separate serial filters.','The chromatic PSF pass runs when needed. Highlight scatter, coherent flare reconstruction and aperture reconstruction are produced from the direct optical image as branches.','Composite combines direct optics, reconstructed aperture and scatter. Diagnostics select alternate views.','Final original/effect blend occurs in linear space, followed by output encoding; the established behavior is preserved.']
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lens Debaser — control layout audit</title><style>body{font:16px/1.55 system-ui;background:#111418;color:#edf0f3;margin:0}main{max-width:1080px;margin:auto;padding:32px}h1{font-size:36px}h2{margin-top:36px}details{border:1px solid #39434c;border-radius:8px;padding:14px;margin:14px 0}details details{background:#181e24}summary{font-size:20px;font-weight:650;cursor:pointer}table{width:100%;border-collapse:collapse}th,td{text-align:left;vertical-align:top;padding:10px;border-bottom:1px solid #39434c}td:first-child{width:65%}small{display:block;color:#aebac5;font-size:13px;margin-top:4px}li{margin:12px 0}p{color:#c4ced6}</style><main><h1>Control layout audit</h1><p>Lens Debaser Projection Test · 2026-10-05 · 160 controls reviewed. Revised candidate presentation; Resolve appearance awaits review. Rendering behavior is unchanged.</p><h2>What changed and why</h2><ol>'''+''.join('<li>'+e(x)+'</li>' for x in findings)+'''</ol><h2>Verified processing structure</h2><ol>'''+''.join('<li>'+e(x)+'</li>' for x in flow)+'''</ol><p>The UI follows editing tasks and major processing stages. Shared fields, depth and lens character remain dependencies, so nesting does not imply every group is a consecutive image-processing pass.</p><h2>Complete revised control tree</h2>'''+''.join(group(g[0]) for g in groups if not g[2])+'''<h2>Validation</h2><p>Complete descriptor coverage, unique IDs, acyclic hierarchy, maximum three group levels, configured-child expansion and important dependencies checked. Candidate host compilation and host-only control mapping checked. No new GPU renders are required for a presentation-only change. Resolve needs a short layout review before integration.</p></main></html>'''
if len(sys.argv)>2 and sys.argv[2]=='1.70':
 page=page.replace('Lens Debaser Projection Test · 2026-10-05','Lens Debaser 1.70 development · 2026-10-05').replace('Revised candidate presentation','Integrated development presentation').replace('Main-release presentation and guide remain unchanged until integration.','The revised presentation is integrated in 1.70 development. The public guide and factory library await review.').replace('Candidate host compilation','Integrated host compilation').replace('Rendering behavior is unchanged.','Rendering behavior matches the passed Projection Test candidate; projection is new relative to released 1.69.').replace('No new GPU renders are required for a presentation-only change. Resolve needs a short layout review before integration.','The UI revision itself is presentation-only. The integrated 1.70 build requires its fresh GPU comparison and Resolve review before factory-preset re-evaluation.')
out=Path(sys.argv[1]);out.parent.mkdir(parents=True,exist_ok=True);out.write_text(page);print(f'Built {out}: {len(controls)} controls, {len(groups)} groups')
