#include "LensDebaserPlugin.h"
#include "LensDebaserMetal.h"
#include "ofxsProcessing.h"
#include "ofxsSupportPrivate.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace {
constexpr const char* kName="Lens Debaser 1.27";
constexpr const char* kIdentifier="com.ldb.LensDebaser";
struct DoubleSpec {const char* id;const char* label;double value,low,high,step;const char* hint;};
const DoubleSpec kSpecs[]={
 {"distortionK1","Primary Distortion",0,-1,1,.001,"Barrel or pincushion distortion."},{"distortionK2","Secondary Distortion",0,-1,1,.001,"Higher-order edge distortion."},
 {"moustacheK3","Moustache",0,-1,1,.001,"Complex wave-shaped radial distortion."},{"anamorphicSqueeze","Anamorphic Field",1,.25,4,.001,"Shapes the complete off-axis lens field; this is not an image desqueeze."},
 {"lateralCARed","Red Fringing",0,-10,10,.01,"Radial red-channel displacement."},{"lateralCABlue","Blue Fringing",0,-10,10,.01,"Radial blue-channel displacement."},
 {"longitudinalCA","Longitudinal Amount",0,0,2,.001,"Near/far focus color separation around local focus transitions."},{"longitudinalCARadius","Longitudinal Radius",4,.5,12,.01,"Feature scale used to identify near- and far-focus transitions."},
 {"vignetteNatural","Natural Vignette",0,0,1,.001,"Smooth cosine-like edge falloff."},{"vignetteOptical","Optical Vignette",0,0,1,.001,"Stronger outer-field transmission loss."},
 {"vignetteMechanical","Mechanical Vignette",0,0,1,.001,"Mixes in the defined image-circle boundary."},{"imageCircleSize","Image Circle Size",1.2,.25,2,.001,"Boundary size used by Mechanical Vignette."},
 {"imageCircleAspect","Image Circle Aspect",1,.25,4,.001,"Boundary aspect used by Mechanical Vignette."},{"imageCircleSoftness","Image Circle Softness",.1,0,1,.001,"Boundary softness used by Mechanical Vignette."},
 {"apertureResponse","Aperture Response",0,0,1,.001,"Mixes in continuous aperture-shaped defocus; external depth holds Focus Depth sharp and increases defocus away from it."},{"apertureRadius","Response Radius",6,0,24,.01,"Spatial size of the aperture response in pixels."},
 {"apertureBladeCurvature","Blade Curvature",.5,0,1,.001,"Rounds polygonal blades toward a circular response."},
 {"apertureRotation","Aperture Rotation",0,-180,180,.1,"Rotates polygonal or oval aperture response in degrees."},{"apertureSoftness","Edge Softness",.5,0,1,.001,"Redistributes pupil energy toward the centre for a progressively softer aperture boundary."},
 {"apertureCatEye","Cat-Eye",0,0,1,.001,"Compresses the pupil radially toward the frame edge."},{"apertureAspect","Pupil Aspect",1,.25,4,.001,"Oval pupil aspect and cat-eye tangential shape."},
 {"cornerSharpnessLoss","Corner Detail Loss",0,0,2,.001,"Progressive off-axis focus loss."},{"astigmatism","Astigmatism",0,-2,2,.001,"Directional off-axis focus split; sign swaps orientation."},
 {"fieldCurvature","Field Curvature",0,0,2,.001,"Curved off-axis focus response."},{"swirl","Swirl",0,-2,2,.001,"Rotational field mapping toward the edges."},
 {"radialSmear","Radial Smear",0,0,2,.001,"Independent radial off-axis spread."},{"tangentialSmear","Tangential Smear",0,0,2,.001,"Independent tangential off-axis spread."},
 {"microContrast","Microcontrast",0,-2,2,.001,"Medium-frequency texture transfer."},{"fineDetail","Fine Detail",0,-2,2,.001,"Fine-frequency transfer without conventional sharpening halos."},
 {"detailEdgeFalloff","Edge Falloff",0,0,2,.001,"Progressive off-axis detail loss."},{"sagittalDetail","Sagittal Detail",0,-2,2,.001,"Radial directional detail transfer."},
 {"tangentialDetail","Tangential Detail",0,-2,2,.001,"Tangential directional detail transfer."},{"detailScale","Detail Scale",1,.25,8,.001,"Feature size affected by Detail Transfer."},
 {"coma","Coma",0,-2,2,.001,"Asymmetric off-axis highlight tail."},{"comaThreshold","Coma Threshold",.6,0,4,.001,"Scene-linear highlight level at which coma begins."},{"sphericalHalo","Spherical Halo",0,0,2,.001,"Smooth highlight halo approximating spherical aberration."},
 {"bloomEnergy","Bloom Amount",0,0,4,.001,"Energy added by highlight bloom."},{"bloomThreshold","Bloom Threshold",1,0,4,.001,"Scene-linear extraction threshold."},
 {"bloomRadius","Bloom Radius",12,0,200,.01,"Bloom spread; requires Bloom Amount."},{"bloomHorizontalStretch","Bloom Stretch",1,1,12,.001,"Horizontal bloom aspect; requires Bloom Amount."},
 {"glareEnergy","Glare Amount",0,0,2,.001,"Energy added by veiling glare."},{"glareRadius","Glare Radius",24,0,200,.01,"Glare spread; requires Glare Amount."},
 {"depthNear","Depth Near",0,0,1000,.001,"Raw depth value mapped to normalized near."},{"depthFar","Depth Far",1,0,1000,.001,"Raw depth value mapped to normalized far."},{"depthFocus","Focus Depth",.5,0,1,.001,"Normalized depth plane held in focus; longitudinal color increases away from this value."},
 {"transmissionColorAmount","Transmission Amount",0,0,1,.001,"Mixes the Transmission Color into lens throughput."},{"glareColorAmount","Glare Color Amount",0,0,1,.001,"Mixes the Glare Color into glare."},
 {"effectBlend","Blend",1,0,1,.001,"Final dry/wet blend in increments of 0.001."}
};

struct Preset {std::string name;std::unordered_map<std::string,double> values;std::array<double,2> center{.5,.5};std::array<double,3> transmission{1,1,1},glare{1,1,1},nearFocus{1,.35,.75},farFocus{.35,1,.65};int apertureShape=0,apertureBladeCount=6,depthMode=0,depthChannel=4;};

class Processor final:public OFX::ImageProcessor{public:explicit Processor(OFX::ImageEffect&e):ImageProcessor(e){} OFX::Image*source=nullptr;LDBOpticsParameters p{};
 void processImagesMetal()override{OfxRectI b=source->getBounds();RunLensDebaserMetal(_pMetalCmdQ,b.x2-b.x1,b.y2-b.y1,p,static_cast<const float*>(source->getPixelData()),static_cast<float*>(_dstImg->getPixelData()));}
 void multiThreadProcessImages(OfxRectI)override{OFX::throwSuiteStatusException(kOfxStatErrUnsupported);}};

class Plugin final:public OFX::ImageEffect{
public:
 explicit Plugin(OfxImageEffectHandle h):ImageEffect(h),handle(h){
  source=fetchClip(kOfxImageEffectSimpleSourceClipName);destination=fetchClip(kOfxImageEffectOutputClipName);
  for(const auto&s:kSpecs)doubles.emplace(s.id,fetchDoubleParam(s.id));
  workingSpace=fetchChoiceParam("workingSpace");quality=fetchChoiceParam("quality");diagnostic=fetchChoiceParam("diagnosticView");presetChoice=fetchChoiceParam("preset");apertureShape=fetchChoiceParam("apertureShape");depthMode=fetchChoiceParam("depthMode");depthChannel=fetchChoiceParam("depthChannel");apertureBladeCount=fetchDoubleParam("apertureBladeCount");
  opticalCenter=fetchDouble2DParam("opticalCenter");transmission=fetchRGBParam("transmissionColor");glare=fetchRGBParam("glareColor");nearFocus=fetchRGBParam("nearFocusColor");farFocus=fetchRGBParam("farFocusColor");updateApertureControls();updateChromaticControls();updateDepthControls();
 }
 void render(const OFX::RenderArguments&a)override{
  if(!a.isEnabledMetalRender)OFX::throwSuiteStatusException(kOfxStatErrUnsupported);
  std::unique_ptr<OFX::Image>src(source->fetchImage(a.time)),dst(destination->fetchImage(a.time));
  if(!src||!dst||src->getPixelDepth()!=OFX::eBitDepthFloat||src->getPixelComponents()!=OFX::ePixelComponentRGBA)OFX::throwSuiteStatusException(kOfxStatErrUnsupported);
  Processor processor(*this);processor.source=src.get();processor.setDstImg(dst.get());processor.setGPURenderArgs(a);processor.setRenderWindow(a.renderWindow);processor.p=parameters(a.time);processor.process();
 }
 bool isIdentity(const OFX::IsIdentityArguments&a,OFX::Clip*&clip,double&time)override{if(value("effectBlend",a.time)<=0){clip=source;time=a.time;return true;}return false;}
 void changedParam(const OFX::InstanceChangedArgs&args,const std::string&name)override{
  if(inPresetChange)return;
  if(name=="loadPreset"){std::string path=ChooseLensDebaserPresetToLoad();if(!path.empty())load(path);return;}
  if(name=="savePreset"){std::string path=ChooseLensDebaserPresetToSave();if(!path.empty())save(path,args.time);return;}
  if(name=="preset"){int index=0;presetChoice->getValue(index);if(index==0)apply(neutralPreset(),true);else if(index>=2&&size_t(index-2)<loaded.size())apply(loaded[index-2],false);return;}
  if(name=="apertureShape"||name=="apertureCatEye")updateApertureControls();
  if(name=="longitudinalCA")updateChromaticControls();
  if(name=="depthMode")updateDepthControls();
  if(name!="workingSpace"&&name!="quality"&&name!="diagnosticView"){
   inPresetChange=true;selectPresetIfNeeded(1);inPresetChange=false;
  }
 }
private:
 double value(const char*id,double t)const{return doubles.at(id)->getValueAtTime(t);}
 LDBOpticsParameters parameters(double t)const{
  LDBOpticsParameters p=LDBNeutralOpticsParameters(0,0);
#define D(x) p.x=float(value(#x,t))
  D(distortionK1);D(distortionK2);D(moustacheK3);D(anamorphicSqueeze);D(lateralCARed);D(lateralCABlue);D(longitudinalCA);D(longitudinalCARadius);D(vignetteNatural);D(vignetteOptical);D(vignetteMechanical);D(imageCircleSize);D(imageCircleAspect);D(imageCircleSoftness);
  D(cornerSharpnessLoss);D(astigmatism);D(coma);D(comaThreshold);D(sphericalHalo);D(fieldCurvature);D(swirl);D(radialSmear);D(tangentialSmear);D(microContrast);D(fineDetail);D(detailEdgeFalloff);D(sagittalDetail);D(tangentialDetail);D(detailScale);
  D(bloomEnergy);D(bloomThreshold);D(bloomRadius);D(bloomHorizontalStretch);D(glareEnergy);D(glareRadius);D(effectBlend);D(transmissionColorAmount);D(glareColorAmount);D(apertureResponse);D(apertureRadius);D(apertureBladeCurvature);D(apertureRotation);D(apertureSoftness);D(apertureCatEye);D(apertureAspect);
#undef D
  double x,y;opticalCenter->getValueAtTime(t,x,y);p.opticalCenter={float(x),float(y)};int s=0,q=0,d=0,a=0,dm=0,dc=0;workingSpace->getValueAtTime(t,s);quality->getValueAtTime(t,q);diagnostic->getValueAtTime(t,d);apertureShape->getValueAtTime(t,a);depthMode->getValueAtTime(t,dm);depthChannel->getValueAtTime(t,dc);p.depthMode=uint32_t(dm);p.depthChannel=uint32_t(dc);p.depthNear=float(value("depthNear",t));p.depthFar=float(value("depthFar",t));p.depthFocus=float(value("depthFocus",t));
  double bladeValue=6;apertureBladeCount->getValueAtTime(t,bladeValue);int blades=std::clamp(int(std::lround(bladeValue)),3,32);p.workingColorSpace=uint32_t(s);p.processingFlags=uint32_t(q)|(uint32_t(d)<<8);p.apertureShape=uint32_t(a);p.apertureBladeCount=uint32_t(blades);double r,g,b;transmission->getValueAtTime(t,r,g,b);p.transmissionColor={float(r),float(g),float(b)};glare->getValueAtTime(t,r,g,b);p.glareColor={float(r),float(g),float(b)};nearFocus->getValueAtTime(t,r,g,b);p.nearFocusColor={float(r),float(g),float(b)};farFocus->getValueAtTime(t,r,g,b);p.farFocusColor={float(r),float(g),float(b)};return p;
 }
 Preset neutralPreset()const{Preset p;p.name="Clean Slate";for(const auto&s:kSpecs)p.values[s.id]=s.value;return p;}
 Preset snapshot(const std::string&name,double time)const{Preset p;p.name=name;for(const auto&s:kSpecs)p.values[s.id]=value(s.id,time);opticalCenter->getValueAtTime(time,p.center[0],p.center[1]);transmission->getValueAtTime(time,p.transmission[0],p.transmission[1],p.transmission[2]);glare->getValueAtTime(time,p.glare[0],p.glare[1],p.glare[2]);nearFocus->getValueAtTime(time,p.nearFocus[0],p.nearFocus[1],p.nearFocus[2]);farFocus->getValueAtTime(time,p.farFocus[0],p.farFocus[1],p.farFocus[2]);apertureShape->getValueAtTime(time,p.apertureShape);depthMode->getValueAtTime(time,p.depthMode);depthChannel->getValueAtTime(time,p.depthChannel);double blades=6;apertureBladeCount->getValueAtTime(time,blades);p.apertureBladeCount=std::clamp(int(std::lround(blades)),3,32);return p;}
 void updateApertureControls(){int shape=0;apertureShape->getValue(shape);double catEye=0;doubles.at("apertureCatEye")->getValue(catEye);bool polygon=shape==1,oval=shape==2;apertureBladeCount->setEnabled(polygon);doubles.at("apertureBladeCurvature")->setEnabled(polygon);doubles.at("apertureRotation")->setEnabled(polygon||oval);doubles.at("apertureAspect")->setEnabled(oval||catEye>1e-8);}
 void updateChromaticControls(){double amount=0;doubles.at("longitudinalCA")->getValue(amount);bool active=amount>1e-8;doubles.at("longitudinalCARadius")->setEnabled(active);nearFocus->setEnabled(active);farFocus->setEnabled(active);}
 void updateDepthControls(){int mode=0;depthMode->getValue(mode);bool active=mode>0;depthMode->setEnabled(true);depthChannel->setEnabled(active);doubles.at("depthNear")->setEnabled(active);doubles.at("depthFar")->setEnabled(active);doubles.at("depthFocus")->setEnabled(active);}
 void setGroupOpen(const char*name,bool open){OfxParamSetHandle set=nullptr;OfxParamHandle param=nullptr;OfxPropertySetHandle props=nullptr;if(OFX::Private::gEffectSuite->getParamSet(handle,&set)==kOfxStatOK&&OFX::Private::gParamSuite->paramGetHandle(set,name,&param,&props)==kOfxStatOK)OFX::Private::gPropSuite->propSetInt(props,kOfxParamPropGroupOpen,0,open?1:0);}
 void updateGroups(const Preset&p){auto active=[&](std::initializer_list<const char*>ids){for(auto id:ids){for(const auto&s:kSpecs)if(std::string(s.id)==id&&std::abs(p.values.at(id)-s.value)>1e-8)return true;}return false;};
  setGroupOpen("geometry",active({"distortionK1","distortionK2","moustacheK3","anamorphicSqueeze","swirl"})||p.center!=std::array<double,2>{.5,.5});
  setGroupOpen("focusField",active({"cornerSharpnessLoss","fieldCurvature","astigmatism","radialSmear","tangentialSmear"}));setGroupOpen("detail",active({"microContrast","fineDetail","detailEdgeFalloff","sagittalDetail","tangentialDetail","detailScale"}));
  setGroupOpen("chromatic",active({"lateralCARed","lateralCABlue","longitudinalCA","longitudinalCARadius"}));setGroupOpen("vignette",active({"vignetteNatural","vignetteOptical","vignetteMechanical","imageCircleSize","imageCircleAspect","imageCircleSoftness"}));setGroupOpen("aperture",active({"apertureResponse","apertureRadius","apertureBladeCurvature","apertureRotation","apertureSoftness","apertureCatEye","apertureAspect"})||p.apertureShape!=0||p.apertureBladeCount!=6);
  setGroupOpen("bloom",active({"bloomEnergy","bloomThreshold","bloomRadius","bloomHorizontalStretch"}));setGroupOpen("glareHalo",active({"glareEnergy","glareRadius","glareColorAmount","sphericalHalo"}));setGroupOpen("transmission",active({"transmissionColorAmount"}));setGroupOpen("offAxis",active({"coma","comaThreshold"}));
  setGroupOpen("opticsSection",active({"distortionK1","distortionK2","moustacheK3","anamorphicSqueeze","swirl","cornerSharpnessLoss","fieldCurvature","astigmatism","radialSmear","tangentialSmear","microContrast","fineDetail","detailEdgeFalloff","sagittalDetail","tangentialDetail","detailScale","lateralCARed","lateralCABlue","longitudinalCA","longitudinalCARadius"})||p.center!=std::array<double,2>{.5,.5});
  setGroupOpen("pupilSection",active({"apertureResponse","apertureRadius","apertureBladeCurvature","apertureRotation","apertureSoftness","apertureCatEye","apertureAspect","vignetteNatural","vignetteOptical","vignetteMechanical","imageCircleSize","imageCircleAspect","imageCircleSoftness"})||p.apertureShape!=0||p.apertureBladeCount!=6);
  setGroupOpen("lightSection",active({"bloomEnergy","bloomThreshold","bloomRadius","bloomHorizontalStretch","glareEnergy","glareRadius","glareColorAmount","sphericalHalo","transmissionColorAmount"}));setGroupOpen("depthGroup",p.depthMode>0);setGroupOpen("advancedSection",active({"coma","comaThreshold"})||p.depthMode>0);}
 void selectPresetIfNeeded(int desired){int current=-1;presetChoice->getValue(current);if(current!=desired)presetChoice->setValue(desired);}
 void apply(const Preset&p,bool clean){inPresetChange=true;beginEditBlock(clean?"Reset Lens Debaser":"Load Lens Debaser Preset");for(const auto&s:kSpecs){auto it=p.values.find(s.id);doubles.at(s.id)->setValue(it==p.values.end()?s.value:it->second);}opticalCenter->setValue(p.center[0],p.center[1]);transmission->setValue(p.transmission[0],p.transmission[1],p.transmission[2]);glare->setValue(p.glare[0],p.glare[1],p.glare[2]);nearFocus->setValue(p.nearFocus[0],p.nearFocus[1],p.nearFocus[2]);farFocus->setValue(p.farFocus[0],p.farFocus[1],p.farFocus[2]);apertureShape->setValue(std::clamp(p.apertureShape,0,2));apertureBladeCount->setValue(std::clamp(p.apertureBladeCount,3,32));depthMode->setValue(std::clamp(p.depthMode,0,5));depthChannel->setValue(std::clamp(p.depthChannel,0,4));selectPresetIfNeeded(clean?0:int(loaded.size()+1));endEditBlock();updateApertureControls();updateChromaticControls();updateDepthControls();updateGroups(p);inPresetChange=false;}
 void refreshChoices(){presetChoice->resetOptions();presetChoice->appendOption("Clean Slate");presetChoice->appendOption("Custom");for(const auto&p:loaded)presetChoice->appendOption(p.name);}
 void load(const std::string&path){std::ifstream f(path);if(!f){sendMessage(OFX::Message::eMessageError,"preset","Unable to open preset file.");return;}Preset p=neutralPreset();p.name=std::filesystem::path(path).stem().string();std::string line;bool valid=false;while(std::getline(f,line)){auto pos=line.find('=');if(pos==std::string::npos)continue;std::string key=line.substr(0,pos),v=line.substr(pos+1);if(key=="LensDebaserPreset"){valid=v=="1";continue;}try{double n=std::stod(v);if(p.values.count(key))p.values[key]=n;else if(key=="apertureShape")p.apertureShape=int(n);else if(key=="apertureBladeCount")p.apertureBladeCount=int(std::lround(n));else if(key=="depthMode")p.depthMode=int(n);else if(key=="depthChannel")p.depthChannel=int(n);else if(key=="opticalCenterX")p.center[0]=n;else if(key=="opticalCenterY")p.center[1]=n;else if(key=="transmissionR")p.transmission[0]=n;else if(key=="transmissionG")p.transmission[1]=n;else if(key=="transmissionB")p.transmission[2]=n;else if(key=="glareR")p.glare[0]=n;else if(key=="glareG")p.glare[1]=n;else if(key=="glareB")p.glare[2]=n;else if(key=="nearFocusR")p.nearFocus[0]=n;else if(key=="nearFocusG")p.nearFocus[1]=n;else if(key=="nearFocusB")p.nearFocus[2]=n;else if(key=="farFocusR")p.farFocus[0]=n;else if(key=="farFocusG")p.farFocus[1]=n;else if(key=="farFocusB")p.farFocus[2]=n;}catch(...){}}if(!valid){sendMessage(OFX::Message::eMessageError,"preset","Not a Lens Debaser .ldbpreset version 1 file.");return;}loaded.push_back(p);refreshChoices();apply(loaded.back(),false);}
 void save(std::string path,double time){if(std::filesystem::path(path).extension()!=".ldbpreset")path+=".ldbpreset";Preset p=snapshot(std::filesystem::path(path).stem().string(),time);std::ofstream f(path);if(!f){sendMessage(OFX::Message::eMessageError,"preset","Unable to save preset file.");return;}f<<"LensDebaserPreset=1\n";for(const auto&s:kSpecs)f<<s.id<<'='<<p.values[s.id]<<'\n';f<<"apertureShape="<<p.apertureShape<<'\n'<<"apertureBladeCount="<<p.apertureBladeCount<<'\n'<<"depthMode="<<p.depthMode<<'\n'<<"depthChannel="<<p.depthChannel<<'\n'<<"opticalCenterX="<<p.center[0]<<"\nopticalCenterY="<<p.center[1]<<'\n'<<"transmissionR="<<p.transmission[0]<<"\ntransmissionG="<<p.transmission[1]<<"\ntransmissionB="<<p.transmission[2]<<'\n'<<"glareR="<<p.glare[0]<<"\nglareG="<<p.glare[1]<<"\nglareB="<<p.glare[2]<<'\n'<<"nearFocusR="<<p.nearFocus[0]<<"\nnearFocusG="<<p.nearFocus[1]<<"\nnearFocusB="<<p.nearFocus[2]<<'\n'<<"farFocusR="<<p.farFocus[0]<<"\nfarFocusG="<<p.farFocus[1]<<"\nfarFocusB="<<p.farFocus[2]<<'\n';loaded.push_back(p);refreshChoices();inPresetChange=true;selectPresetIfNeeded(int(loaded.size()+1));inPresetChange=false;}
 OfxImageEffectHandle handle;OFX::Clip *source=nullptr,*destination=nullptr;OFX::ChoiceParam *workingSpace=nullptr,*quality=nullptr,*diagnostic=nullptr,*presetChoice=nullptr,*apertureShape=nullptr,*depthMode=nullptr,*depthChannel=nullptr;OFX::DoubleParam*apertureBladeCount=nullptr;OFX::Double2DParam*opticalCenter=nullptr;OFX::RGBParam *transmission=nullptr,*glare=nullptr,*nearFocus=nullptr,*farFocus=nullptr;std::unordered_map<std::string,OFX::DoubleParam*>doubles;std::vector<Preset>loaded;bool inPresetChange=false;
};

OFX::DoubleParamDescriptor* addDouble(OFX::ImageEffectDescriptor&d,const DoubleSpec&s,OFX::GroupParamDescriptor&g,OFX::PageParamDescriptor&p){auto*x=d.defineDoubleParam(s.id);x->setLabels(s.label,s.label,s.label);x->setScriptName(s.id);x->setHint(s.hint);x->setDefault(s.value);x->setRange(s.low,s.high);x->setDisplayRange(s.low,s.high);x->setIncrement(s.step);x->setParent(g);p.addChild(*x);return x;}
OFX::GroupParamDescriptor* addGroup(OFX::ImageEffectDescriptor&d,OFX::PageParamDescriptor&p,const char*id,const char*label,bool open=false){auto*g=d.defineGroupParam(id);g->setLabels(label,label,label);g->setOpen(open);p.addChild(*g);return g;}
}

LensDebaserPluginFactory::LensDebaserPluginFactory():PluginFactoryHelper(kIdentifier,1,27){}
void LensDebaserPluginFactory::describe(OFX::ImageEffectDescriptor&d){d.setLabels(kName,kName,kName);d.getPropertySet().propSetString(kOfxPropIcon,"com.ldb.LensDebaser.png",1,false);d.setPluginGrouping("LDB");d.setPluginDescription("Perceptual cinematic lens character for Apple Silicon and DaVinci Resolve.");d.addSupportedContext(OFX::eContextFilter);d.addSupportedContext(OFX::eContextGeneral);d.addSupportedBitDepth(OFX::eBitDepthFloat);d.setSupportsMetalRender(true);d.setSupportsTiles(false);d.setSupportsMultiResolution(false);d.setTemporalClipAccess(false);d.setHostFrameThreading(false);d.setRenderTwiceAlways(false);d.setNoSpatialAwareness(false);}
void LensDebaserPluginFactory::describeInContext(OFX::ImageEffectDescriptor&d,OFX::ContextEnum){
 auto*src=d.defineClip(kOfxImageEffectSimpleSourceClipName);src->addSupportedComponent(OFX::ePixelComponentRGBA);src->setSupportsTiles(false);auto*dst=d.defineClip(kOfxImageEffectOutputClipName);dst->addSupportedComponent(OFX::ePixelComponentRGBA);dst->setSupportsTiles(false);
 auto*page=d.definePageParam("Controls");auto*setup=page;auto*optics=page;auto*pupil=page;auto*light=page;auto*advanced=page;
 auto*setupSection=addGroup(d,*page,"setupSection","Setup",true);auto*opticsSection=addGroup(d,*page,"opticsSection","Optics",true);auto*pupilSection=addGroup(d,*page,"pupilSection","Pupil & Vignette");auto*lightSection=addGroup(d,*page,"lightSection","Light");auto*advancedSection=addGroup(d,*page,"advancedSection","Advanced");auto*output=addGroup(d,*page,"output","Blend",true);
 auto*presetGroup=addGroup(d,*setup,"presetGroup","Presets",true);presetGroup->setParent(*setupSection);auto*preset=d.defineChoiceParam("preset");preset->setLabels("Preset","Preset","Preset");preset->appendOption("Clean Slate");preset->appendOption("Custom");preset->setDefault(0);preset->setParent(*presetGroup);setup->addChild(*preset);auto*load=d.definePushButtonParam("loadPreset");load->setLabels("Load","Load","Load");load->setParent(*presetGroup);setup->addChild(*load);auto*save=d.definePushButtonParam("savePreset");save->setLabels("Save","Save","Save");save->setParent(*presetGroup);setup->addChild(*save);
 auto*processing=addGroup(d,*setup,"processing","Processing",true);processing->setParent(*setupSection);auto*ws=d.defineChoiceParam("workingSpace");ws->setLabels("Input Working Space","Input Working Space","Input Working Space");for(auto*s:{"ACEScg (Linear AP1)","ACEScct","DaVinci Wide Gamut / Intermediate","ARRI LogC3 EI800","ARRI LogC4"})ws->appendOption(s);ws->setDefault(2);ws->setHint("Must match the image encoding entering Lens Debaser. Not stored in presets.");ws->setParent(*processing);setup->addChild(*ws);
 auto*q=d.defineChoiceParam("quality");q->setLabels("Scatter Quality","Scatter Quality","Scatter Quality");q->setHint("Controls bloom, glare and halo refinement. Direct optical processing is unchanged.");q->appendOption("Balanced");q->appendOption("Fast");q->appendOption("High");q->setDefault(0);q->setParent(*processing);setup->addChild(*q);auto*diag=d.defineChoiceParam("diagnosticView");diag->setLabels("Diagnostic View","Diagnostic View","Diagnostic View");diag->setHint("Scatter Only is black when no bloom, glare or halo energy is present. Direct Optics Only excludes those scatter layers. Depth Input displays the normalized optional depth clip.");for(auto*s:{"Off","Difference (Amplified)","Scatter Only","Direct Optics Only","Depth Input"})diag->appendOption(s);diag->setDefault(0);diag->setParent(*processing);setup->addChild(*diag);
 auto*geometry=addGroup(d,*optics,"geometry","Geometry");auto*focus=addGroup(d,*optics,"focusField","Focus & Field");auto*detail=addGroup(d,*optics,"detail","Detail Transfer");auto*chromatic=addGroup(d,*optics,"chromatic","Chromatic Aberration");geometry->setParent(*opticsSection);focus->setParent(*opticsSection);detail->setParent(*opticsSection);chromatic->setParent(*opticsSection);auto*aperture=addGroup(d,*pupil,"aperture","Aperture",true);auto*vignette=addGroup(d,*pupil,"vignette","Vignette");aperture->setParent(*pupilSection);vignette->setParent(*pupilSection);auto*bloom=addGroup(d,*light,"bloom","Bloom");auto*glareHalo=addGroup(d,*light,"glareHalo","Glare & Halo");auto*transmissionGroup=addGroup(d,*light,"transmission","Transmission");bloom->setParent(*lightSection);glareHalo->setParent(*lightSection);transmissionGroup->setParent(*lightSection);auto*offAxis=addGroup(d,*advanced,"offAxis","Off-Axis Character");offAxis->setParent(*advancedSection);auto*depthGroup=addGroup(d,*advanced,"depthGroup","Depth Input");depthGroup->setParent(*advancedSection);
 auto*dm=d.defineChoiceParam("depthMode");dm->setLabels("Depth Interpretation","Depth Interpretation","Depth Interpretation");for(auto*s:{"Depth-Free","Near White","Near Black","Linear Camera Z","Inverse Z / Disparity","Logarithmic Z"})dm->appendOption(s);dm->setDefault(0);dm->setHint("External modes read depth packed into a selected channel of the incoming RGBA image; Alpha is recommended. Depth drives Aperture Response, Longitudinal Amount, Spherical Halo, and Bloom/Glare occlusion. Depth-Free preserves the local approximation.");dm->setParent(*depthGroup);advanced->addChild(*dm);auto*dc=d.defineChoiceParam("depthChannel");dc->setLabels("Depth Source Channel","Depth Source Channel","Depth Source Channel");for(auto*s:{"Luminance","Red","Green","Blue","Alpha"})dc->appendOption(s);dc->setDefault(4);dc->setHint("Alpha is the Resolve-compatible depth carrier. Pack a grayscale depth map into source alpha upstream; Lens Debaser restores opaque output alpha while external depth is active.");dc->setParent(*depthGroup);advanced->addChild(*dc);
 auto*shape=d.defineChoiceParam("apertureShape");shape->setLabels("Aperture Shape","Aperture Shape","Aperture Shape");shape->appendOption("Circular");shape->appendOption("Polygon");shape->appendOption("Oval / Anamorphic");shape->setDefault(0);shape->setHint("Selects the continuous aperture-response approximation; Aperture Response must be above zero.");shape->setParent(*aperture);pupil->addChild(*shape);
 auto*center=d.defineDouble2DParam("opticalCenter");center->setLabels("Optical Center","Optical Center","Optical Center");center->setDimensionLabels("X","Y");center->setDefault(.5,.5);center->setRange(0,0,1,1);center->setDisplayRange(0,0,1,1);center->setParent(*geometry);optics->addChild(*center);
 for(const auto&s:kSpecs){std::string id=s.id;OFX::GroupParamDescriptor*g=geometry;OFX::PageParamDescriptor*p=optics;if(id=="cornerSharpnessLoss"||id=="fieldCurvature"||id=="astigmatism"||id=="radialSmear"||id=="tangentialSmear")g=focus;else if(id=="microContrast"||id=="fineDetail"||id=="detailEdgeFalloff"||id=="sagittalDetail"||id=="tangentialDetail"||id=="detailScale")g=detail;else if(id=="lateralCARed"||id=="lateralCABlue"||id=="longitudinalCA"||id=="longitudinalCARadius")g=chromatic;else if(id=="depthNear"||id=="depthFar"||id=="depthFocus"){g=depthGroup;p=advanced;}else if(id.rfind("aperture",0)==0){g=aperture;p=pupil;}else if(id.rfind("vignette",0)==0||id.rfind("imageCircle",0)==0){g=vignette;p=pupil;}else if(id.rfind("bloom",0)==0){g=bloom;p=light;}else if(id.rfind("glare",0)==0||id=="sphericalHalo"){g=glareHalo;p=light;}else if(id.rfind("transmission",0)==0){g=transmissionGroup;p=light;}else if(id=="coma"||id=="comaThreshold"){g=offAxis;p=advanced;}else if(id=="effectBlend"){g=output;p=advanced;}if(id=="apertureBladeCurvature"){auto*blades=d.defineDoubleParam("apertureBladeCount");blades->setLabels("Blade Count","Blade Count","Blade Count");blades->setScriptName("apertureBladeCount");blades->setHint("Whole-number blade count used by Polygon shape; high counts approach a circular iris.");blades->setDefault(6);blades->setRange(3,32);blades->setDisplayRange(3,32);blades->setIncrement(1);blades->setDigits(0);blades->setParent(*aperture);pupil->addChild(*blades);}addDouble(d,s,*g,*p);}
 auto addColor=[&](const char*id,const char*label,OFX::GroupParamDescriptor&g,OFX::PageParamDescriptor&p,double r=1,double green=1,double b=1){auto*x=d.defineRGBParam(id);x->setLabels(label,label,label);x->setDefault(r,green,b);x->setRange(0,2,0,2,0,2);x->setDisplayRange(0,1,0,1,0,1);x->setParent(g);p.addChild(*x);};addColor("transmissionColor","Transmission Color",*transmissionGroup,*light);addColor("glareColor","Glare Color",*glareHalo,*light);addColor("nearFocusColor","Near-Focus Color",*chromatic,*optics,1,.35,.75);addColor("farFocusColor","Far-Focus Color",*chromatic,*optics,.35,1,.65);
}
OFX::ImageEffect*LensDebaserPluginFactory::createInstance(OfxImageEffectHandle h,OFX::ContextEnum){return new Plugin(h);}void OFX::Plugin::getPluginIDs(PluginFactoryArray&a){static LensDebaserPluginFactory f;a.push_back(&f);}
